name: Deploy to EC2 Host

on:
  push:
    branches:
      - main

  jobs:
    deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Run bash command
      run: ls -al

    - name: Copy files to EC2
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_HOST_NAME }}
        password: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: ./
        target: ./

    - name: Copy files to var directory
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_HOST_NAME }}
        password: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
        sudo cp -r * /var/www/html
        sudo systemctl restart nginx
        
